/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: ["class"],
	content: ["src/**/*.{ts,tsx}"],
	theme: {
		container: {
			center: true,
			padding: "2rem",
			screens: {
				"2xl": "1400px",
			},
		},
		extend: {
			colors: {
				primary: {
					25: "rgb(var(--primary-25), <alpha-value>);",
					50: "rgb(var(--primary-50), <alpha-value>);",
					100: "rgb(var(--primary-100), <alpha-value>);",
					200: "rgb(var(--primary-200), <alpha-value>);",
					300: "rgb(var(--primary-300), <alpha-value>);",
					400: "rgb(var(--primary-400), <alpha-value>);",
					500: "rgb(var(--primary-500), <alpha-value>);",
					600: "rgb(var(--primary-600), <alpha-value>);",
					700: "rgb(var(--primary-700), <alpha-value>);",
					800: "rgb(var(--primary-800), <alpha-value>);",
					900: "rgb(var(--primary-900), <alpha-value>);",
					"25f": "rgb(var(--primary-700), <alpha-value>)",
					"50f": "rgb(var(--primary-700), <alpha-value>)",
					"100f": "rgb(var(--primary-700), <alpha-value>)",
					"200f": "rgb(var(--primary-700), <alpha-value>)",
					"300f": "rgb(var(--white), <alpha-value>)",
					"400f": "rgb(var(--white), <alpha-value>)",
					"500f": "rgb(var(--white), <alpha-value>)",
					"600f": "rgb(var(--white), <alpha-value>)",
					"700f": "rgb(var(--white), <alpha-value>)",
					"800f": "rgb(var(--white), <alpha-value>)",
					"900f": "rgb(var(--white), <alpha-value>)",
				},
				gray: {
					25: "rgb(var(--gray-25), <alpha-value>);",
					50: "rgb(var(--gray-50), <alpha-value>);",
					100: "rgb(var(--gray-100), <alpha-value>);",
					200: "rgb(var(--gray-200), <alpha-value>);",
					300: "rgb(var(--gray-300), <alpha-value>);",
					400: "rgb(var(--gray-400), <alpha-value>);",
					500: "rgb(var(--gray-500), <alpha-value>);",
					600: "rgb(var(--gray-600), <alpha-value>);",
					700: "rgb(var(--gray-700), <alpha-value>);",
					800: "rgb(var(--gray-800), <alpha-value>);",
					900: "rgb(var(--gray-900), <alpha-value>);",
					"25f": "rgb(var(--gray-700), <alpha-value>)",
					"50f": "rgb(var(--gray-700), <alpha-value>)",
					"100f": "rgb(var(--gray-700), <alpha-value>)",
					"200f": "rgb(var(--gray-700), <alpha-value>)",
					"300f": "rgb(var(--white), <alpha-value>)",
					"400f": "rgb(var(--white), <alpha-value>)",
					"500f": "rgb(var(--white), <alpha-value>)",
					"600f": "rgb(var(--white), <alpha-value>)",
					"700f": "rgb(var(--white), <alpha-value>)",
					"800f": "rgb(var(--white), <alpha-value>)",
					"900f": "rgb(var(--white), <alpha-value>)",
				},
				error: {
					25: "rgb(var(--error-25), <alpha-value>);",
					50: "rgb(var(--error-50), <alpha-value>);",
					100: "rgb(var(--error-100), <alpha-value>);",
					200: "rgb(var(--error-200), <alpha-value>);",
					300: "rgb(var(--error-300), <alpha-value>);",
					400: "rgb(var(--error-400), <alpha-value>);",
					500: "rgb(var(--error-500), <alpha-value>);",
					600: "rgb(var(--error-600), <alpha-value>);",
					700: "rgb(var(--error-700), <alpha-value>);",
					800: "rgb(var(--error-800), <alpha-value>);",
					900: "rgb(var(--error-900), <alpha-value>);",
					"25f": "rgb(var(--error-700), <alpha-value>)",
					"50f": "rgb(var(--error-700), <alpha-value>)",
					"100f": "rgb(var(--error-700), <alpha-value>)",
					"200f": "rgb(var(--error-700), <alpha-value>)",
					"300f": "rgb(var(--white), <alpha-value>)",
					"400f": "rgb(var(--white), <alpha-value>)",
					"500f": "rgb(var(--white), <alpha-value>)",
					"600f": "rgb(var(--white), <alpha-value>)",
					"700f": "rgb(var(--white), <alpha-value>)",
					"800f": "rgb(var(--white), <alpha-value>)",
					"900f": "rgb(var(--white), <alpha-value>)",
				},
				warning: {
					25: "rgb(var(--warning-25), <alpha-value>);",
					50: "rgb(var(--warning-50), <alpha-value>);",
					100: "rgb(var(--warning-100), <alpha-value>);",
					200: "rgb(var(--warning-200), <alpha-value>);",
					300: "rgb(var(--warning-300), <alpha-value>);",
					400: "rgb(var(--warning-400), <alpha-value>);",
					500: "rgb(var(--warning-500), <alpha-value>);",
					600: "rgb(var(--warning-600), <alpha-value>);",
					700: "rgb(var(--warning-700), <alpha-value>);",
					800: "rgb(var(--warning-800), <alpha-value>);",
					900: "rgb(var(--warning-900), <alpha-value>);",
					"25f": "rgb(var(--warning-700), <alpha-value>)",
					"50f": "rgb(var(--warning-700), <alpha-value>)",
					"100f": "rgb(var(--warning-700), <alpha-value>)",
					"200f": "rgb(var(--warning-700), <alpha-value>)",
					"300f": "rgb(var(--white), <alpha-value>)",
					"400f": "rgb(var(--white), <alpha-value>)",
					"500f": "rgb(var(--white), <alpha-value>)",
					"600f": "rgb(var(--white), <alpha-value>)",
					"700f": "rgb(var(--white), <alpha-value>)",
					"800f": "rgb(var(--white), <alpha-value>)",
					"900f": "rgb(var(--white), <alpha-value>)",
				},
				success: {
					25: "rgb(var(--success-25), <alpha-value>);",
					50: "rgb(var(--success-50), <alpha-value>);",
					100: "rgb(var(--success-100), <alpha-value>);",
					200: "rgb(var(--success-200), <alpha-value>);",
					300: "rgb(var(--success-300), <alpha-value>);",
					400: "rgb(var(--success-400), <alpha-value>);",
					500: "rgb(var(--success-500), <alpha-value>);",
					600: "rgb(var(--success-600), <alpha-value>);",
					700: "rgb(var(--success-700), <alpha-value>);",
					800: "rgb(var(--success-800), <alpha-value>);",
					900: "rgb(var(--success-900), <alpha-value>);",
					"25f": "rgb(var(--success-700), <alpha-value>)",
					"50f": "rgb(var(--success-700), <alpha-value>)",
					"100f": "rgb(var(--success-700), <alpha-value>)",
					"200f": "rgb(var(--success-700), <alpha-value>)",
					"300f": "rgb(var(--white), <alpha-value>)",
					"400f": "rgb(var(--white), <alpha-value>)",
					"500f": "rgb(var(--white), <alpha-value>)",
					"600f": "rgb(var(--white), <alpha-value>)",
					"700f": "rgb(var(--white), <alpha-value>)",
					"800f": "rgb(var(--white), <alpha-value>)",
					"900f": "rgb(var(--white), <alpha-value>)",
				},
				secondary: {
					25: "rgb(var(--secondary-25), <alpha-value>);",
					50: "rgb(var(--secondary-50), <alpha-value>);",
					100: "rgb(var(--secondary-100), <alpha-value>);",
					200: "rgb(var(--secondary-200), <alpha-value>);",
					300: "rgb(var(--secondary-300), <alpha-value>);",
					400: "rgb(var(--secondary-400), <alpha-value>);",
					500: "rgb(var(--secondary-500), <alpha-value>);",
					600: "rgb(var(--secondary-600), <alpha-value>);",
					700: "rgb(var(--secondary-700), <alpha-value>);",
					800: "rgb(var(--secondary-800), <alpha-value>);",
					900: "rgb(var(--secondary-900), <alpha-value>);",
					"25f": "rgb(var(--secondary-700), <alpha-value>)",
					"50f": "rgb(var(--secondary-700), <alpha-value>)",
					"100f": "rgb(var(--secondary-700), <alpha-value>)",
					"200f": "rgb(var(--secondary-700), <alpha-value>)",
					"300f": "rgb(var(--white), <alpha-value>)",
					"400f": "rgb(var(--white), <alpha-value>)",
					"500f": "rgb(var(--white), <alpha-value>)",
					"600f": "rgb(var(--white), <alpha-value>)",
					"700f": "rgb(var(--white), <alpha-value>)",
					"800f": "rgb(var(--white), <alpha-value>)",
					"900f": "rgb(var(--white), <alpha-value>)",
				},
			},
			borderRadius: {
				lg: "var(--radius)",
				md: "calc(var(--radius) - 2px)",
				sm: "calc(var(--radius) - 4px)",
			},
			fontFamily: {},
			keyframes: {
				"accordion-down": {
					from: { height: 0 },
					to: { height: "var(--radix-accordion-content-height)" },
				},
				"accordion-up": {
					from: { height: "var(--radix-accordion-content-height)" },
					to: { height: 0 },
				},
			},
			animation: {
				"accordion-down": "accordion-down 0.2s ease-out",
				"accordion-up": "accordion-up 0.2s ease-out",
			},
		},
	},
	plugins: [],
};
